// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHD3rSeA4NVNcftygU88KrIpSzt6neaaw',
    appId: '1:939135892784:web:18a640373d8763f84edcf5',
    messagingSenderId: '939135892784',
    projectId: 'farequest',
    authDomain: 'farequest.firebaseapp.com',
    storageBucket: 'farequest.firebasestorage.app',
    measurementId: 'G-D47ZNSDF5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMW5tyIOVoeY8B8e7EOgHxMxxsGzGvnOw',
    appId: '1:939135892784:android:52cad3624843e4964edcf5',
    messagingSenderId: '939135892784',
    projectId: 'farequest',
    storageBucket: 'farequest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFsQAc_C8e0TGm6vONoi-ssmf7BMaTMQ4',
    appId: '1:939135892784:ios:daa79339d5f6db494edcf5',
    messagingSenderId: '939135892784',
    projectId: 'farequest',
    storageBucket: 'farequest.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsQAc_C8e0TGm6vONoi-ssmf7BMaTMQ4',
    appId: '1:939135892784:ios:daa79339d5f6db494edcf5',
    messagingSenderId: '939135892784',
    projectId: 'farequest',
    storageBucket: 'farequest.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHD3rSeA4NVNcftygU88KrIpSzt6neaaw',
    appId: '1:939135892784:web:845afa3bcc2529cb4edcf5',
    messagingSenderId: '939135892784',
    projectId: 'farequest',
    authDomain: 'farequest.firebaseapp.com',
    storageBucket: 'farequest.firebasestorage.app',
    measurementId: 'G-5ZN16HPW4B',
  );
}
